In [2]:
import pandas as pd
import numpy as np

In [22]:
movie=pd.read_csv('data/movie.csv', index_col='movie_title')

In [23]:
movie.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
Avatar,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Pirates of the Caribbean: At World's End,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Spectre,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [25]:
movie_2hours=movie['duration']>120

In [26]:
movie_2hours.sum()

1039

In [27]:
len(movie)

4916

In [32]:
crit_a=movie.imdb_score>8

In [33]:
crit_a.head()

movie_title
Avatar                                        False
Pirates of the Caribbean: At World's End      False
Spectre                                       False
The Dark Knight Rises                          True
Star Wars: Episode VII - The Force Awakens    False
Name: imdb_score, dtype: bool

In [35]:
crit_b=movie.content_rating=='PG-13'
#crit_c=(movie.title_year<=2000 | movie.title_year>=2010)

In [36]:
crit_c=(movie.title_year<=2000) | (movie.title_year>=2010)

In [37]:
crit_final=crit_a & crit_b & crit_c

In [38]:
crit_final

movie_title
Avatar                                        False
Pirates of the Caribbean: At World's End      False
Spectre                                       False
The Dark Knight Rises                          True
Star Wars: Episode VII - The Force Awakens    False
                                              ...
Signed Sealed Delivered                       False
The Following                                 False
A Plague So Pleasant                          False
Shanghai Calling                              False
My Date with Drew                             False
Length: 4916, dtype: bool

In [46]:
movie[crit_final]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,2.500000e+08,2012.0,23000.0,8.5,2.35,164000
The Avengers,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,2.200000e+08,2012.0,21000.0,8.1,1.85,123000
Captain America: Civil War,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,2.500000e+08,2016.0,19000.0,8.2,2.35,72000
Guardians of the Galaxy,Color,James Gunn,653.0,121.0,571.0,3000.0,Vin Diesel,14000.0,333130696.0,Action|Adventure|Sci-Fi,...,1097.0,English,USA,PG-13,1.700000e+08,2014.0,14000.0,8.1,2.35,96000
Interstellar,Color,Christopher Nolan,712.0,169.0,22000.0,6000.0,Anne Hathaway,11000.0,187991439.0,Adventure|Drama|Sci-Fi,...,2725.0,English,USA,PG-13,1.650000e+08,2014.0,11000.0,8.6,2.35,349000
Inception,Color,Christopher Nolan,642.0,148.0,22000.0,23000.0,Tom Hardy,29000.0,292568851.0,Action|Adventure|Sci-Fi|Thriller,...,2803.0,English,USA,PG-13,1.600000e+08,2010.0,27000.0,8.8,2.35,175000
The Martian,Color,Ridley Scott,568.0,151.0,0.0,372.0,Donald Glover,13000.0,228430993.0,Adventure|Drama|Sci-Fi,...,1023.0,English,USA,PG-13,1.080000e+08,2015.0,801.0,8.1,2.35,153000
Jurassic Park,Color,Steven Spielberg,308.0,127.0,14000.0,191.0,Ariana Richards,967.0,356784000.0,Adventure|Sci-Fi|Thriller,...,895.0,English,USA,PG-13,6.300000e+07,1993.0,610.0,8.1,1.85,19000
Forrest Gump,Black and White,Robert Zemeckis,149.0,142.0,0.0,194.0,Siobhan Fallon Hogan,15000.0,329691196.0,Comedy|Drama,...,1398.0,English,USA,PG-13,5.500000e+07,1994.0,294.0,8.8,2.35,59000
Indiana Jones and the Last Crusade,Color,Steven Spielberg,149.0,127.0,14000.0,440.0,Julian Glover,11000.0,197171806.0,Action|Adventure|Fantasy,...,477.0,English,USA,PG-13,4.800000e+07,1989.0,844.0,8.3,2.35,0
The Sixth Sense,Color,M. Night Shyamalan,234.0,107.0,0.0,766.0,Haley Joel Osment,13000.0,293501675.0,Drama|Mystery|Thriller,...,2073.0,English,USA,PG-13,4.000000e+07,1999.0,3000.0,8.1,1.85,14000
The Help,Color,Tate Taylor,373.0,146.0,150.0,2000.0,Bryce Dallas Howard,15000.0,169705587.0,Drama,...,460.0,English,USA,PG-13,2.500000e+07,2011.0,3000.0,8.1,1.85,75000
Warrior,Color,Gavin O'Connor,317.0,140.0,149.0,581.0,Frank Grillo,27000.0,13651662.0,Drama|Sport,...,514.0,English,USA,PG-13,2.500000e+07,2011.0,798.0,8.2,2.35,77000
Princess Mononoke,Color,Hayao Miyazaki,174.0,134.0,6000.0,745.0,Jada Pinkett Smith,893.0,2298191.0,Adventure|Animation|Fantasy,...,570.0,Japanese,Japan,PG-13,2.400000e+09,1997.0,851.0,8.4,1.85,11000
The Imitation Game,Color,Morten Tyldum,454.0,114.0,77.0,305.0,Rory Kinnear,19000.0,91121452.0,Biography|Drama|Thriller|War,...,608.0,English,UK,PG-13,1.400000e+07,2014.0,393.0,8.1,2.35,165000
Once Upon a Time in the West,Color,Sergio Leone,164.0,145.0,0.0,392.0,Woody Strode,973.0,NaN,Western,...,565.0,English,Italy,PG-13,5.000000e+06,1968.0,423.0,8.6,2.35,10000
Samsara,Color,Ron Fricke,115.0,102.0,330.0,0.0,Balinese Tari Legong Dancers,48.0,2601847.0,Documentary|Music,...,69.0,None,USA,PG-13,4.000000e+06,2011.0,0.0,8.5,2.35,26000
"Batman: The Dark Knight Returns, Part 2",Color,Jay Oliva,44.0,148.0,41.0,739.0,Mark Valley,2000.0,NaN,Action|Animation|Crime|Sci-Fi|Thriller,...,55.0,English,USA,PG-13,3.500000e+06,2013.0,774.0,8.4,NaN,5000
Inside Job,Color,Charles Ferguson,171.0,105.0,117.0,18.0,George W. Bush,13000.0,4311834.0,Crime|Documentary,...,129.0,English,USA,PG-13,NaN,2010.0,125.0,8.3,2.35,63000
Growing Up Smith,Color,Frank Lotito,NaN,102.0,5.0,259.0,Jake Busey,3000.0,NaN,Comedy|Drama|Family,...,1.0,English,USA,PG-13,2.000000e+06,2015.0,660.0,8.2,1.85,232
Queen of the Mountains,Color,Sadyk Sher-Niyaz,16.0,135.0,135.0,0.0,Aziz Muradillayev,0.0,NaN,Action|Biography|Drama|History,...,24.0,English,Kyrgyzstan,PG-13,1.400000e+06,2014.0,0.0,8.7,2.35,0
A Separation,Color,Asghar Farhadi,354.0,123.0,0.0,620.0,Leila Hatami,786.0,7098492.0,Drama|Mystery,...,264.0,Persian,Iran,PG-13,5.000000e+05,2011.0,712.0,8.4,1.85,48000
Hoop Dreams,Color,Steve James,53.0,170.0,23.0,2.0,Arthur Agee,7.0,7830611.0,Documentary|Drama|Sport,...,74.0,English,USA,PG-13,7.000000e+05,1994.0,6.0,8.3,1.33,0

In [41]:
len(filter_movie)

23

In [43]:
sel_col=['imdb_score', 'content_rating', 'title_year']

In [45]:
movie.loc[crit_final,sel_col]

                                         imdb_score content_rating  title_year
movie_title
The Dark Knight Rises                           8.5          PG-13      2012.0
The Avengers                                    8.1          PG-13      2012.0
Captain America: Civil War                      8.2          PG-13      2016.0
Guardians of the Galaxy                         8.1          PG-13      2014.0
Interstellar                                    8.6          PG-13      2014.0
Inception                                       8.8          PG-13      2010.0
The Martian                                     8.1          PG-13      2015.0
Jurassic Park                                   8.1          PG-13      1993.0
Forrest Gump                                    8.8          PG-13      1994.0
Indiana Jones and the Last Crusade              8.3          PG-13      1989.0
The Sixth Sense                                 8.1          PG-13      1999.0
The Help                                        8.1          PG-13      2011.0
Warrior                                         8.2          PG-13      2011.0
Princess Mononoke                               8.4          PG-13      1997.0
The Imitation Game                              8.1          PG-13      2014.0
Once Upon a Time in the West                    8.6          PG-13      1968.0
Samsara                                         8.5          PG-13      2011.0
Batman: The Dark Knight Returns, Part 2         8.4          PG-13      2013.0
Inside Job                                      8.3          PG-13      2010.0
Growing Up Smith                                8.2          PG-13      2015.0
Queen of the Mountains                          8.7          PG-13      2014.0
A Separation                                    8.4          PG-13      2011.0
Hoop Dreams                                     8.3          PG-13      1994.0

In [47]:
#SQL

In [3]:
emp=pd.read_csv('data/employee.csv')

In [4]:
emp.head()

,UNIQUE_ID,POSITION_TITLE,DEPARTMENT,BASE_SALARY,RACE,EMPLOYMENT_TYPE,GENDER,EMPLOYMENT_STATUS,HIRE_DATE,JOB_DATE
0,0,ASSISTANT DIRECTOR (EX LVL),Municipal Courts Department,121862.0,Hispanic/Latino,Full Time,Female,Active,2006-06-12,2012-10-13
1,1,LIBRARY ASSISTANT,Library,26125.0,Hispanic/Latino,Full Time,Female,Active,2000-07-19,2010-09-18
2,2,POLICE OFFICER,Houston Police Department-HPD,45279.0,White,Full Time,Male,Active,2015-02-03,2015-02-03
3,3,ENGINEER/OPERATOR,Houston Fire Department (HFD),63166.0,White,Full Time,Male,Active,1982-02-08,1991-05-25
4,4,ELECTRICIAN,General Services Department,56347.0,White,Full Time,Male,Active,1989-06-19,1994-10-22

In [15]:
depts=['Houston Police Department-HPD','Houston Fire Department (HFD)','Library']
sel_cols=['UNIQUE_ID', 'DEPARTMENT', 'GENDER','BASE_SALARY']

In [18]:
qs="DEPARTMENT in @depts " \
   "and GENDER =='Female' " \
   "and 8000 <= BASE_SALARY <=120000"
emp_filter=emp.query(qs)
emp_filter[sel_cols]

      UNIQUE_ID                     DEPARTMENT  GENDER  BASE_SALARY
1             1                        Library  Female      26125.0
55           55  Houston Police Department-HPD  Female      34757.0
61           61  Houston Fire Department (HFD)  Female      96668.0
67           67  Houston Police Department-HPD  Female      66614.0
113         113  Houston Police Department-HPD  Female      66614.0
...         ...                            ...     ...          ...
1963       1963                        Library  Female      51542.0
1964       1964  Houston Police Department-HPD  Female      47996.0
1971       1971  Houston Police Department-HPD  Female      45279.0
1978       1978  Houston Police Department-HPD  Female      27914.0
1991       1991  Houston Police Department-HPD  Female      44429.0

[190 rows x 4 columns]

In [16]:
query_string = "DEPARTMENT in @depts " \
               "and GENDER == 'Female' " \
               "and 80000 <= BASE_SALARY <= 120000"
        
emp_filtered = emp.query(query_string)
emp_filtered[sel_cols].head()

     UNIQUE_ID                     DEPARTMENT  GENDER  BASE_SALARY
61          61  Houston Fire Department (HFD)  Female      96668.0
136        136  Houston Police Department-HPD  Female      81239.0
367        367  Houston Police Department-HPD  Female      86534.0
474        474  Houston Police Department-HPD  Female      91181.0
513        513  Houston Police Department-HPD  Female      81239.0

In [66]:
crit_dept=emp.DEPARTMENT.isin(depts)

In [67]:
crit_gender=emp.GENDER=='Female'

In [68]:
crit_sal=(emp.BASE_SALARY>=80000) & \
         (emp.BASE_SALARY<=120000)

In [69]:
crit_emp_final=crit_dept&crit_gender&crit_sal

In [71]:
crit_emp_final

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

In [72]:
emp[crit_emp_final]

,UNIQUE_ID,POSITION_TITLE,DEPARTMENT,BASE_SALARY,RACE,EMPLOYMENT_TYPE,GENDER,EMPLOYMENT_STATUS,HIRE_DATE,JOB_DATE
61,61,IT PROJECT MANAGER,Houston Fire Department (HFD),96668.0,Black or African American,Full Time,Female,Active,1998-04-07,2006-01-28
136,136,POLICE SERGEANT,Houston Police Department-HPD,81239.0,White,Full Time,Female,Active,1991-02-04,2005-02-12
367,367,POLICE LIEUTENANT,Houston Police Department-HPD,86534.0,Black or African American,Full Time,Female,Active,1993-06-21,2012-05-09
474,474,POLICE LIEUTENANT,Houston Police Department-HPD,91181.0,Asian/Pacific Islander,Full Time,Female,Active,1989-12-11,2014-11-13
513,513,POLICE SERGEANT,Houston Police Department-HPD,81239.0,Black or African American,Full Time,Female,Active,1991-04-11,2013-10-31
564,564,POLICE SERGEANT,Houston Police Department-HPD,81239.0,White,Full Time,Female,Active,1995-04-10,2004-10-21
595,595,STAFF PSYCHOLOGIST,Houston Police Department-HPD,99953.0,White,Full Time,Female,Active,2012-05-01,2012-05-01
937,937,POLICE SERGEANT,Houston Police Department-HPD,81239.0,Black or African American,Full Time,Female,Active,1994-08-29,2010-01-07
954,954,POLICE LIEUTENANT,Houston Police Department-HPD,91181.0,White,Full Time,Female,Active,1990-04-23,2012-03-31
1118,1118,POLICE CAPTAIN,Houston Police Department-HPD,104455.0,White,Full Time,Female,Active,1991-08-05,2011-10-05
1165,1165,DEPUTY ASSISTANT DIRECTOR (EXECUTIVE LEV,Library,107763.0,Black or African American,Full Time,Female,Active,1993-11-16,2014-03-15
1519,1519,POLICE LIEUTENANT,Houston Police Department-HPD,91181.0,Black or African American,Full Time,Female,Active,1993-02-01,2014-03-06
1565,1565,POLICE SERGEANT,Houston Police Department-HPD,81239.0,White,Full Time,Female,Active,2014-12-11,2007-01-18
1622,1622,POLICE LIEUTENANT,Houston Police Department-HPD,91181.0,Black or African American,Full Time,Female,Active,1994-01-31,2012-04-25

In [76]:
select_columns = ['UNIQUE_ID', 'DEPARTMENT', 'GENDER', 'BASE_SALARY']
emp.loc[crit_emp_final, select_columns].head()

     UNIQUE_ID                     DEPARTMENT  GENDER  BASE_SALARY
61          61  Houston Fire Department (HFD)  Female      96668.0
136        136  Houston Police Department-HPD  Female      81239.0
367        367  Houston Police Department-HPD  Female      86534.0
474        474  Houston Police Department-HPD  Female      91181.0
513        513  Houston Police Department-HPD  Female      81239.0

In [78]:
criteria_dept = emp.DEPARTMENT.isin(['Houston Police Department-HPD', 'Houston Fire Department (HFD)'])
criteria_gender = emp.GENDER == 'Female'
criteria_sal = (emp.BASE_SALARY >= 80000) & (emp.BASE_SALARY <= 120000)

In [79]:
criteria_final = criteria_dept & criteria_gender & criteria_sal

In [80]:
query_string = "DEPARTMENT in @depts " \
               "and GENDER == 'Female' " \
               "and 80000 <= BASE_SALARY <= 120000"
        
emp_filtered = emp.query(query_string)
emp_filtered[select_columns].head()

     UNIQUE_ID                     DEPARTMENT  GENDER  BASE_SALARY
61          61  Houston Fire Department (HFD)  Female      96668.0
136        136  Houston Police Department-HPD  Female      81239.0
367        367  Houston Police Department-HPD  Female      86534.0
474        474  Houston Police Department-HPD  Female      91181.0
513        513  Houston Police Department-HPD  Female      81239.0

In [81]:
movie = pd.read_csv('data/movie.csv', index_col='movie_title')
facebook_likes = movie['actor_1_facebook_likes'].dropna()
facebook_likes.head()

movie_title
Avatar                                         1000.0
Pirates of the Caribbean: At World's End      40000.0
Spectre                                       11000.0
The Dark Knight Rises                         27000.0
Star Wars: Episode VII - The Force Awakens      131.0
Name: actor_1_facebook_likes, dtype: float64

In [82]:
criteria_high = facebook_likes < 20000
criteria_high.mean()

0.9085353432470972

In [83]:
facebook_likes < 20000

movie_title
Avatar                                         True
Pirates of the Caribbean: At World's End      False
Spectre                                        True
The Dark Knight Rises                         False
Star Wars: Episode VII - The Force Awakens     True
                                              ...
Signed Sealed Delivered                        True
The Following                                  True
A Plague So Pleasant                           True
Shanghai Calling                               True
My Date with Drew                              True
Name: actor_1_facebook_likes, Length: 4909, dtype: bool

In [84]:
facebook_likes.where(criteria_high,other=20000)

movie_title
Avatar                                         1000.0
Pirates of the Caribbean: At World's End      20000.0
Spectre                                       11000.0
The Dark Knight Rises                         20000.0
Star Wars: Episode VII - The Force Awakens      131.0
                                               ...
Signed Sealed Delivered                         637.0
The Following                                   841.0
A Plague So Pleasant                              0.0
Shanghai Calling                                946.0
My Date with Drew                                86.0
Name: actor_1_facebook_likes, Length: 4909, dtype: float64